### ISSUE TITLE
getting error message in "admin rate confirm.php" file

### ISSUE THREAD

**Issue by Jannat-Jabeen** [Shivananda199/Fake-Product-Review-Monitoring-and-Product-Evaluation-using-Opinion-Mining#1]
i get an error message (undefined variable: rating   , in C:\xampp\ita_project\admin\admin-rate-confirm.php on line 23) while click on "rate" by admin ,

**Comment by shivananda199** [comment]
Please have a column 'rating' created in **products** table in your database

**Comment by Vaishnaviyelure** [comment]
error in test . py file

**Comment by Vaishnaviyelure** [comment]
Real reviews are also showing in delete fake reviews page

**Comment by ankitakamble03** [comment]
Where is imageStyle .css file

**Comment by Vaishnaviyelure** [comment]
No in admin folder test.py file one more question based on which criteria it is showing review are fake.

**Comment by ankitakamble03** [comment]
My problem is image style .css file or link is not their,so I can't see the
picture in project
