### ISSUE TITLE
not found

### ISSUE THREAD

**Issue by srinjoy26** [Shivananda199/Fake-Product-Review-Monitoring-and-Product-Evaluation-using-Opinion-Mining#2]
.\Desktop\final year project\Fake-Product-Review-Monitoring-and-Product-Evaluation-using-Opinion-Mining-master\fake\fakepro\admin>python test.py
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    with open("product_reviews.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'product_reviews.json'

please give me a solution

**Comment by iota-008** [comment]
create a json file with reviews

**Comment by sindooraprakash** [comment]
json file

**Comment by shivananda199** [comment]
yes, as suggested by [iota-008](https://github.com/iota-008), create a sample product_reviews.json file with a collection of positive and negative reviews.
